# release/**  --> any branch strt with 'release'
on:
    push: 
        branches:
            - main
            - "release/**"
        paths:
            - "sec/**"
            # and so on... more pathes
    pull_request: 
        branches:
            - main
            - "release/**"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6.1.0

            - name: Run Tests
              run:
                npm test